repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -  id: check-yaml
    -  id: end-of-file-fixer
    -  id: trailing-whitespace
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    - id: black
          language_version: python3.8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.2
    hooks:
    - id: isort
      additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    - id: mypy
      files: sas7bdat_converter/
