name: Backend Linting
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: "Python Poetry Action"
      working-directory: ./backend/app
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip -e .
        python3 -m pip install -r requirements-dev.txt
    - name: Isort check
      working-directory: ./sas7bdat_converter
      run: |
        isort sas7bdat_converter tests --check-only
    - name: Black check
      working-directory: ./sas7bdat_converter
      run: |
        black sas7bdat_converter tests --check
    - name: Lint with flake8
      working-directory: ./sas7bdat_converter
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 sas7bdat_converter tests --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 sas7bdat_converter tests --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
    - name: mypy check
      working-directory: ./sas7bdat_converter
      run: |
        mypy sas7bdat_converter
