name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies Windows
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install -r requirements-dev.txt
    - name: Install dependencies Linux/Mac
      if: matrix.os  != 'windows-latest')
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .
        python3 -m pip install -r requirements-dev.txt
    - name: Test with pytest
      run: |
        pytest
    - name: Upload coverage
      uses: codecov/codecov-action@v1
