name: Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  Testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry on Windows
      if: matrix.os == 'windows-latest'
      run: |
        (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -
        echo "::add-path::%USERPROFILE%\.poetry\bin"
    - name: Install Poetry and add to path on Linux/Mac
      if: matrix.os != 'windows-latest'
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
    - name: Install Dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest --cov=sas7bdat_converter --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
